### ISSUE TITLE
Set custom file name in options object

### ISSUE THREAD

**Issue by boakenfull** [hasanayan/craco-plugin-single-spa-application#10]
Not really an issue, but it would be useful to set the `filename` in the options object, instead of using the `orgName-projectName`.

**Comment by hasanayan** [comment]
Hi @boakenfull please feel free to open a PR for that

**Comment by felipeplets** [comment]
@boakenfull is this still a desired feature request for your use case?

**Comment by felipeplets** [comment]
Implemented in #11
