### ISSUE TITLE
Feature request: adding `libraryTarget` as a params to the plugin options

### ISSUE THREAD

**Issue by m-nathani** [hasanayan/craco-plugin-single-spa-application#12]
I really liked and appreciate the effort you put to create a single-spa  plugin.. however why only limiting to single-spa ?

with the same config we and adding `libraryTarget` to the params of the config we can make apps target `umd` ,  or `window` etc.. ?

**Comment by felipeplets** [comment]
The objective of the plugin is to setup a project specifically for Single SPA compatibility.

I recommend using CRACO with WebPack only to add other `libraryTarget` as this should be easy just using the available documentation.
