### ISSUE TITLE
Issues related to Webpack externals 

### ISSUE THREAD

**Issue by felipeplets** [hasanayan/craco-plugin-single-spa-application#18]
There are three issues related to the  webpack externals in this library. I have decided to talk about all the 3 in this issue instead of opening different issues.

**1. Overriding externals**

The first issue is that it overrides externals set by other plugins or by the user in the configuration. 
I have a use case where I bundle the application as a Single SPA app or as a standalone app, I want both to have the same externals so my expectation is that the code below would work as expected. 

```
const singleSpaApplicationPlugin = require("craco-plugin-single-spa-application")

const plugins = []

if (process.env.MICRO) {
  plugins.push({
    plugin: singleSpaApplicationPlugin,
    options: {
      orgName: "myOrg",
      projectName: "myApp",
      entry: "src/single-spa-index.tsx",
    },
  })
}

module.exports = {
  plugins,
  webpack: {
    configure: {
      externals: {
        lodash: "lodash",
      },
    },
  },
}
```

This work in standalone mode but not on the single spa mode because the plugin ignores the default externals and override it. The solution was to change the code to have the externals as a constant and assign it in both places. This still is not ideal as other plugins changing or adding externals wouldn't be respected.

```
const singleSpaApplicationPlugin = require("craco-plugin-single-spa-application")

const plugins = []
const externals = {
  lodash: "lodash",
}

if (process.env.MICRO) {
  plugins.push({
    plugin: singleSpaApplicationPlugin,
    options: {
      orgName: "myOrg",
      projectName: "myApp",
      entry: "src/single-spa-index.tsx",
      externals,
    },
  })
}

module.exports = {
  plugins,
  webpack: {
    configure: {
      externals,
    },
  },
}
```

This solution above still don't work as expected because of the next issue.

**2. Change accepted types**

The externals signature on webpack documentation is: 
> string object function RegExp [string, object, function, RegExp]
> source [https://webpack.js.org/configuration/externals/](https://webpack.js.org/configuration/externals/)

The plugin signature assumes it will always be an array, so to make above code work I would need to make externals always to be an array.

**3. redefining a standard API**

As the plugin exposes the externals changing the signature this will need to keep the external compatibility to whatever WebPack does, as this is a standard well defined API for externals my proposal is to avoid redefining it and instead make use of the existing one.

**Comment by felipeplets** [comment]
PR #20 address the 3 issues mentioned above. This is a breaking change so I can provide the migration steps when it gets released.

**Comment by JeffWeim** [comment]
Hi @felipeplets - I'm trying to use this plugin in a CRA4 project. The project is importing a single-spa utility module. When running in integrated mode everything works as expected.

When running in standalone mode, I'm getting a `Module not found: Can't resolve [...]`. I was curious if this PR solved that issue and if so what the `craco.config.js` looks like for using a single-spa utility module in both integrated and standalone modes?
