### ISSUE TITLE
Invalid parser object - parser has an unknown property 'system'

### ISSUE THREAD

**Issue by dbgordon09** [hasanayan/craco-plugin-single-spa-application#23]
Hey guys! 👋

So I just bumped up to `craco-plugin-single-spa-application@2.0.0` and received the following
```
Module not found: ValidationError: Invalid parser object. Asset Modules Plugin has been initialized using a parser object that does not match the API schema.
 - parser has an unknown property 'system'. These properties are valid:
   object { dataUrlCondition? }
   -> Parser options for asset modules.
```
It seems like the specified module rule has an incompatible parser set.

I think it is referring to this line
https://github.com/hasanayan/craco-plugin-single-spa-application/blob/43546623f020ab992c07ec7ba146a92c448a4c94/src/index.js#L90

Thought I would bring this to your attention!
I am running:
`"@craco/craco": "^7.0.0-alpha.3",`
`"react-scripts": "^5.0.1",`

Let me know if there is anything else you need or how I might be able to help 💪

Keep up the great work!

**Comment by felipeplets** [comment]
Hi @dbgordon09 thank you for letting us know. 

I have tried reproducing your issue following the steps below and the application works fine for me: 
- Create new CRA App using v5
- Add `single-spa-react@4.6.1`, `@craco/craco@7.0.0-alpha.3` and `craco-plugin-single-spa-application@2.0.0`
- Change package.json from `react-scripts` to `craco` as per craco install steps
- Add the src/single-spa-index.tsx
- Add craco.config.js with the example configuration in this repo README.md
- tried running `npm run build`

Is there something different for you from the steps above? Would it be possible that you share the code reproducing the issue?

**Comment by dbgordon09** [comment]
Hey @felipeplets! 🙋‍♂️

Thanks so much for getting back to me so quickly, much appreciated.

The steps you mentioned are very similar to the steps that I took, with slight deviations.

* Created a new CRA with v`5.0.1` of `react-scripts`.
* Added `craco` v`7.0.0-alpha.3`.
* Added `craco-plugin-single-spa-application@2.0.0` and `single-spa-react@4.6.1`.
* Added `src/single-spa-index.tsx`.
Here is the contents of that file: (Even though I don't think this is in anyway related)
```
import App from 'App';
import React from 'react';
import ReactDOM from 'react-dom';
import singleSpaReact from 'single-spa-react';

const reactLifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: App,
  errorBoundary: (_err, _errInfo, _props) => (
      <div>Something went wrong! 😥</div>
  ),
});

export const bootstrap = reactLifecycles.bootstrap;
export const mount = reactLifecycles.mount;
export const unmount = reactLifecycles.unmount;
```
* Created `craco.config.ts` to allow `start` to be overridden.
* Created `craco-single-spa.config.js` to be referenced when building the app specifically for use in `single-spa`.

Here is the script that invokes the build process:
`"build:single-spa": "craco build --config craco-single-spa.config.js",`
Here is the contents of that config:
```
const singleSpaApplicationPlugin = require('craco-plugin-single-spa-application');

module.exports = {
  plugins: [
    {
      plugin: singleSpaApplicationPlugin,
      options: {
        orgName: 'eysbp',
        projectName: 'sdm',
        entry: 'src/single-spa-index.tsx',
        outputFilename: 'single-spa-build.js',
      },
    },
  ],
};
```
I am expecting it to create a `single-spa-build.js` but it gives me the above error.

Also while I have you here am I understanding correctly that if I go
`"start:single-spa": "craco start --config craco-single-spa.config.js",` if should serve said `js` file on port 3000? Or is that incorret?

**Comment by felipeplets** [comment]
Thank you for additional details. I have tried a couple of different situations but still wasn't able to reproduce. 

A couple more questions that occured to me:
- Which OS are you using? 
- What NodeJS version?
- Are you in a monorepo?
- Can you share your package.json content?
- Can you share a repo with the code reproducing the issue?

**Comment by orkisz** [comment]
@felipeplets For me the same issue came up as soon as I try to import JSON file into any component by writing:

`import STH from './test.json'`

The error message says:
```
ERROR in ./src/App.tsx 7:0-30
Module not found: ValidationError: Invalid parser object. Json Modules Plugin has been initialized using a parser object that does not match the API schema.
 - parser has an unknown property 'system'. These properties are valid:
   object { parse? }
```

**Comment by fupengl** [comment]
> 

`react-scripts@5.x` This configuration should be deleted.

You can try https://github.com/fupengl/react-app-rewired-single-spa, compatible with wp5.

**Comment by felipeplets** [comment]
Thank you @orkisz and @fupengl. I was able to reproduce the error  and fix it. 

Just released version 2.0.1 of the library with the fix. Please folks let me know if you find any other issues.

**Comment by dbgordon09** [comment]
@felipeplets - Great job!

Just to confirm I tried creating a new react app and retrying with the same config and everything worked great. 🎉

It seems Webpack incorrectly throws this error when building for production as it is set to bail on error when not in `development` mode. So this error is somewhat of a red herring and has nothing to do with your wonderful plugin. Seems it was actually type errors that caused the TSC to fail and by extension Webpack.

**Comment by felipeplets** [comment]
Amazing! Thank you for confirming it @dbgordon09 and for helping make the plugin better.

**Comment by orkisz** [comment]
@felipeplets I've just upgraded, everything works like a charm! Thank you :)
