### ISSUE TITLE
Cra4 Fast Refresh will not work on React components, only css

### ISSUE THREAD

**Issue by salvoravida** [hasanayan/craco-plugin-single-spa-application#7]
Hi, I have a SingleSpa 5.9 root app, a microfrontend (cra4) in dev mode with your plugin.

The problem is the the hmr (that on CRA4 is done via Fast-Refresh) works only for Css but not for React Components.

I had to add old react-hot-loader  
export default hot(App) for HMR on the microfrontend. (plus the env var WDS_SOCKET_PORT)

Any idea?

**Comment by salvoravida** [comment]
Problem solved: you need to use dev version of react

      "imports": {
        "react": "https://cdn.jsdelivr.net/npm/react@16.14.0/umd/react.development.js",
        "react-dom": "https://cdn.jsdelivr.net/npm/react-dom@16.14.0/umd/react-dom.development.js",

**Comment by Baozhen-Yin** [comment]
> imports

Where is this code added

**Comment by JeffWeim** [comment]
@salvoravida Did you make this update to the development bundles in the container single-spa application? Were there any other changes required?
